config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :userss, :only => [:index]
  resources :posts do
    collection do
      get 'filter/:tag_name' => 'posts#filter'
    end
  end

  root 'posts#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user
      if user.has_role? "admin"
        can :manage, :all
      elsif user
        can :write, :posts
        can :manage, Post do |post|
          post.user_id == user.id
        end
      end
    end
    can :read, :posts
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  resourcify
  has_and_belongs_to_many :tags
  belongs_to :user
  validates :author, presence: true
  validates :title, presence: true
  validates :body, presence: true
  validates :tags, presence: { message: "must have at least one tag" }
  validates_associated :tags

  def tags_string
    tags.map(&:name).join(",")
  end

  def tags_string=(new_value)
    tag_names = new_value.split(/[,\s]+/)
    self.tags = tag_names.map { |name| Tag.where('name = ?', name).first || Tag.create(:name => name) }
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  validates :name, presence: true
  has_and_belongs_to_many :posts
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  validates :email, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :posts
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "50x50>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) << :avatar
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    console
    @posts = Post.order(updated_at: :desc)
    @tags = sorted_tags.reverse
  end

  # GET /posts/filter/tag_name
  def filter
    @posts = Post.joins(:tags).where("tags.name" => params[:tag_name]).order(updated_at: :desc)
    @tags = sorted_tags.reverse
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    can_manage_post
  end

  # POST /posts
  # POST /posts.json
  def create
    can_create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    can_manage_post
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
    delete_unused_tags
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    can_manage_post
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
    delete_unused_tags
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:author, :title, :body, :tags_string)
  end

  # find unused tags and delete them
  def delete_unused_tags
    ActiveRecord::Base.connection.execute(
      "delete from tags where id in(
        select t.id from tags as t left join posts_tags as pt on pt.tag_id = t.id where pt.tag_id is null
      )"
    )
  end

  def sorted_tags
    Tag.all.map { |tag| { :name => tag.name, :count => tag.posts.count } }.sort! { |a, b| a[:count] <=> b[:count] }
  end

  # raise exception if cannot write posts
  def can_create
    raise ActionController::RoutingError 'Forbidden' if current_user.nil? || cannot?(:write, :posts)
    true
  end

  # raise exception if cannot manage
  def can_manage_post
    raise ActionController::RoutingError 'Forbidden' if current_user.nil? || cannot?(:manage, @post)
    true
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tag
    @tag = Tag.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/controllers/userss_controller.rb
class UserssController < ApplicationController
  def index
    raise ActionController::RoutingError, 'Forbidden' if current_user.nil? || !current_user.has_role?("admin")
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/userss_helper.rb
module UserssHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user %>
    <%= link_to "Sign out", destroy_user_session_path(), :method => :delete %> 
    <%= link_to "Edit profile", edit_user_registration_path() %>
    <%= link_to "Posts", root_path() %> 
    <% if current_user.has_role? "admin" %>
      <%= link_to "Users", userss_index_path %>
    <% end %>
  <% else %>
    <%= link_to "Sign in", new_user_session_path() %> or 
    <%= link_to "sign up", new_user_registration_path() %>.
  <% end %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :tags_string %><br>
    <%= f.text_field :tags_string %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/filter.html.erb
<p id="notice"><%= notice %></p>


<h1>Listing Posts</h1>
<p><%= link_to("All", posts_path) %> or by tags: <% @tags.each do |tag| %><%= link_to(tag[:name], posts_path + '/filter/' + tag[:name]) %> <% end %></p>
<table border=1>
  <thead>
    <tr>
      <th>Author</th>
      <th>Title</th>
      <th>Body</th>
      <th>Tags</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr ID="post-row-<%= post.id %>">
        <td class="post-author"><%= post.author %></td>
        <td class="post-title"><%= post.title %></td>
        <td class="post-body"><%= post.body %></td>
        <td class="post-tags"><%= post.tags_string %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Listing Posts</h1>
<p>Tags: <% @tags.each do |tag| %><%= link_to(tag[:name], posts_path + '/filter/' + tag[:name]) %> <% end %></p>
<table border=1>
  <thead>
    <tr>
      <th>Avatar</th>
      <th>Author</th>
      <th>Title</th>
      <th>Body</th>
      <th>Tags</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr ID="post-row-<%= post.id %>">
        <td class="user-avatar"><%= image_tag post.user.avatar.url(:thumb) %></td>
        <td class="post-author"><%= post.author %></td>
        <td class="post-title"><%= post.title %></td>
        <td class="post-body"><%= post.body %></td>
        <td class="post-tags"><%= post.tags_string %></td>
        <td>
          <%= link_to 'Show', post_path(post) %><% if can?(:manage, post) %>,
            <%= link_to 'Edit', edit_post_path(post) %>, 
            <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can? :write, :posts %>
  <%= link_to 'New Post', new_post_path %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @post.author %>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @post.tags_string %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tags</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/userss/index.html.erb
<h1>Listing users</h1>
<table border=1>
  <thead>
    <tr>
      <th>Avatar</th>
      <th>Mail</th>
      <th>created</th>
      <th>confirmed</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr ID="user-row-<%= user.id %>">
        <td class="user-avatar"><%= image_tag user.avatar.url(:thumb) %></td>
        <td class="user-email"><%= user.email %></td>
        <td class="user-created_at"><%= user.created_at %></td>
        <td>
          <% if user.confirmed_at.nil? %>
            <%= link_to 'Confirm', user_confirmation_path + '?confirmation_token=' + user.confirmation_token, target: "_blank" %>
          <% else %>
            <%= user.confirmed_at %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>